# Generated by Django 3.2.10 on 2022-02-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taborapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photomodel',
            name='file',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
