# Generated by Django 3.2.10 on 2022-02-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taborapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomodel',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails/%Y/%m/%d/'),
        ),
    ]
