# Generated by Django 3.2.10 on 2022-03-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taborapp', '0002_photomodel_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='docs/')),
                ('filetype', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='file',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails/'),
        ),
    ]
